[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200</content>
<parameter name="filePath">/Users/ashfrantz/Documents/GitHub/The-Agency_Coming-Soon/netlify.toml
